# Generated by Django 2.0.1 on 2018-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ean', models.PositiveIntegerField(default=0)),
                ('nome', models.CharField(max_length=64)),
                ('descrizione', models.CharField(blank=True, max_length=512, null=True)),
                ('prezzo', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='foto_prodotti')),
            ],
        ),
    ]
