# Generated by Django 2.0.1 on 2018-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterField(
            model_name='articolo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foto_prodotti'),
        ),
    ]
